# Generated by Django 4.2.19 on 2025-03-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttype',
            name='photo',
            field=models.ImageField(default=1, upload_to='type_photo'),
            preserve_default=False,
        ),
    ]
