# Generated by Django 4.2.19 on 2025-03-19 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_restauranttype_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Dish Name')),
                ('photo', models.ImageField(upload_to='recommended_dishes/', verbose_name='Photo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_dishes', to='frontend.restaurant', verbose_name='Restaurant')),
            ],
        ),
    ]
